prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: status-page
        static_configs:
          - targets: ['status-page.default.svc.cluster.local:80']
        metrics_path: /metrics
        scrape_interval: 30s
grafana:
  enabled: true
  adminPassword: admin
defaultRules:
  rules:
    prometheus:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager-operated.monitoring.svc:9093']
